### ISSUE TITLE
bug with audio when skipping time in avi

### ISSUE THREAD

**Issue by Skalke** [Cpasjuste/pplay#11]
i tried to watch some movie....and stopped it on some time...but after stopping video and skipping some time....my audio-output become nothing and i could saw only video without sounds...fix it plz

**Comment by Cpasjuste** [comment]
I think this problem is related to the media resolution/bitrate. It will be worked on.

**Comment by Skalke** [comment]
Still not fixed on 1.3 version...

**Comment by Cpasjuste** [comment]
Hi @Skalke, i think the problem may be fixed in pPlay 1.4, as you can now (and should) use low buffering option for most media (and it's a lot faster, which help with audio too).

**Comment by Skalke** [comment]
Hi, again @Cpasjuste ... It's still not fixed in 1.4 with low buffering...still see same things on 1.4 pPlay...idk how u will debug this...but i can test your builds with my videos

**Comment by Cpasjuste** [comment]
I think you previously said it was working fine with low buffering no? I think I would need a step be step direction to reproduce the problem, as English is not my primilary language I'm not sure to correctly understand :)

**Comment by Skalke** [comment]
*`low-bitrate videos it's restarting audio-output always after skipping and resuming (givinng more time, but working).`* look at screen...mp4 files is working fine problem only with avi with audio ac3 384kb/s ... maybe it also could be with another avi videos...i didn't test it with anothers...

**Comment by Skalke** [comment]
new info about avi trouble....sound is missing and in this...
Quality: DVDRip
Format: AVI
Video Codec: DivX
Audio codec: MP3
Video: 640x480, 25 fps, XviD ~ 1485 kbps avg, 0.12 bit / pixel
Audio:
44 kHz, AC3 Dolby Digital, 2/0 (L, R) ch, ~ 128.00 kbps avg RUS

**Comment by Cpasjuste** [comment]
Thanks for the continual report @Skalke. I'm actually refactoring audio, it may help. I'll let you know as soon as it's done!

**Comment by Cpasjuste** [comment]
Hi, it's now fixed in 2.0, thanks :)

**Comment by Skalke** [comment]
yeah it's done! Great job @Cpasjuste ! Now in v2.1 all avi movies is working great without overclock! Thanks a lot for this great player
