### ISSUE TITLE
bug with time format

### ISSUE THREAD

**Issue by Skalke** [Cpasjuste/pplay#14]
![2019011020001300-da63280140b1530cd17755515d814cfe](https://user-images.githubusercontent.com/10077834/50984449-f37a8b80-1512-11e9-8474-6e9d94d07d04.jpg)
it's 20:00

**Comment by Cpasjuste** [comment]
Thanks for the report! Fixed here https://github.com/Cpasjuste/pplay/commit/bbf0f337d270a8dd19eec3ab1c7c8c063a74d2e5
