### ISSUE TITLE
.ass subtitles overlapped towards end of line

### ISSUE THREAD

**Issue by fullmetal1** [Cpasjuste/pplay#15]
I was testing pplay, and when I tried playing "[AK-Submarines] GIRLS und PANZER der FILM v2 [835F8E63].mkv", the subtitle lines would be abruptly cut off towards the right of the screen with a copy of the leftmost text.

It appears to be a rendering error, as the text can be cut off mid letter

**Comment by fullmetal1** [comment]
fixed with latest release

**Comment by Cpasjuste** [comment]
Hi, it's fixed in 2.0, thanks!
