### ISSUE TITLE
Add HEVC support (harware playback)

### ISSUE THREAD

**Issue by blue240** [Cpasjuste/pplay#19]
As of now, HEVC file playback is very choppy. The Tegra X1 processor that the Switch uses has support for hardware HEVC decoding according to [https://www.nvidia.com/object/tegra-x1-processor.html](https://www.nvidia.com/object/tegra-x1-processor.html).

Thank you.

**Comment by Cpasjuste** [comment]
Hi, it won't be possible anytime soon, sorry.
