### ISSUE TITLE
pPlay 3.0 bad resolution

### ISSUE THREAD

**Issue by darkxex** [Cpasjuste/pplay#38]
please check the app on a nintendo switch and you will see that only a quarter of the screen is visible.

**Comment by darkxex** [comment]
![screen](https://user-images.githubusercontent.com/17991404/68778842-7c21f680-0612-11ea-9339-58bf25874f4d.jpg)

**Comment by peijie7788** [comment]
Can cofirm that this is happening to me too.

**Comment by HieubyDooby** [comment]
this is happening for me too

**Comment by grrbhen** [comment]
Can confirm this is happening to me as well.

**Comment by StaticCC** [comment]
Same here, really sucks, please fix <3

**Comment by lesca** [comment]
Same screen here.

**Comment by Continous** [comment]
I am unable to reproduce this bug, is this still an issue?
