### ISSUE TITLE
pPlay v3.1 breaks ftp service

### ISSUE THREAD

**Issue by nxgitter** [Cpasjuste/pplay#40]
pPlay v3.1 breaks FTP access functionality for me. 

I checked the CFG file and deleted the cache folder as troubleshooting steps. I checked my firewall settings. The work around is to use the 'hippy dave' GBAtemp resigned v2.1, FTP works again without issue using the same CFG file, I just overwrite pplay.nro and it works. Copying over the v3.1 pplay.nro breaks it again and the Network option from the menu simply appears empty when accessed.

Can you please look into this and why v3.1 is breaking FTP support? Until then I'll have to stay back using the HD signed V2.1 until fixed. Thanks for your time and effort.

PC OS/soft: Windows 10 64-Bit, FileZilla FTP Server
Switch: FW 8.0.1 Emunand CFW Atmosphere 0.9.4

Whats not working: FTP access in pplay v3.1
Temp workaround: Use v2.1 / Hippydave v2.1 (for 9.0.1 FW)

**Comment by dimag0g** [comment]
Same bug when connecting to `vsftpd` on Debian Buster.

**Comment by mercury501** [comment]
Having the same problem, ftp doesn't even try to authenticate.
Tried 3.0 as well, nothing.

**Comment by projexa** [comment]
hello, i have the same problem to, have you find a solution? in fact, each time you load the homevrew, the config was resetting.
excuse my bad English i was Belgium, thank very mutch

**Comment by mercury501** [comment]
I resolved using http actually, on linux I just made a startup script who does cd in the directory where video are, and then 
`python3 -m http.server 8000`

then in pplay.cfg change the line:
`NETWORK = "http://SERVER_IP:8000/";`

changing SERVER_IP accordingly.

**Comment by projexa** [comment]
thank i'm testing that

**Comment by dimag0g** [comment]
@mercury501 I don't get it: how can an HTTP server provide FTP access? This doesn't make sense.

**Comment by mercury501** [comment]
I meant that's a workaround. The command listed above serves a directory over http, as I needed to access videos on a Linux machine this workaround works for me. To my knowledge ftp still doesn't work.

**Comment by dimag0g** [comment]
@mercury501 Speaking of workarounds, copying files to the SD card works fine too. That doesn't mean FTP doesn't need fixing.

**Comment by mercury501** [comment]
Wow, I bow to your superior logic.

**Comment by lordelan** [comment]
@Cpasjuste Please fix FTP. You had it working in older releases so you should be able to without much work.
That would be an amazing christmas present!

**Comment by lesca** [comment]
same problem here. FTP doesn't show anything, even if I allow anonymous access. pplay version 3.4 (latest one by now)

**Comment by montikun** [comment]
Still no solution or workaround for the newer versions?

**Comment by montikun** [comment]
+1. I wish FTP started working again. Until then, I'm staying on 2.1.

**Comment by Heniker** [comment]
Looks like FTP is working for me on v3.5

**Comment by Cpasjuste** [comment]
Hi, yes it should now work on 3.5, closing.
