### ISSUE TITLE
WebDav OR Plex support , the best solution to NAS / Online Play

### ISSUE THREAD

**Issue by bao3** [Cpasjuste/pplay#46]
Hi guy,

pPlay is very good for offline play , I use MPV on my macOS also . I read some issues of this repo , some people requested NAS support/UPNP support/https /http basic auth and so on.

pPlay support http method ,but it is not good enough for online play . I suggest to add WebDav support which could match all the needs of LAN/ internet/NAS . Switch only support 1080P ,so the performance in the LAN between UPNP/ WebDAV/HTTP /SMB  is the same .

Alternatively, could support Plex API

**Comment by Cardellos** [comment]
I know it's not what you wanna hear but i got it working with my plex server through FTP, but i had to download the 2.1v
https://gbatemp.net/attachments/pplay-v2-1-900-hidfix-catoverflow-7z.184115/
honestly, i think this is abandoned or Cpasjuste does not read/care about this anymore

**Comment by bao3** [comment]
@Cardellos thanks , I would try FTP method .
