### ISSUE TITLE
Not working with 11.0.x firmware

### ISSUE THREAD

**Issue by cruzer619** [Cpasjuste/pplay#57]
crashes when opening on the latest firmware 11.0.x.  Ppl are saying "probably needs to be compiled with latest libnx."

**Comment by Cpasjuste** [comment]
Hi, 
Thanks for the information, i'll try to fix this soon (this week if possible).

**Comment by cruzer619** [comment]
I updated to atmo 0.16.1 and 11.0.1, now its working again....
