### ISSUE TITLE
Program not playing videos at all

### ISSUE THREAD

**Issue by civismo** [Cpasjuste/pplay#7]
The menu works fine but a 720p .mkv video froze the whole thing and a 480p .mp4 didn't play.

**Comment by Cpasjuste** [comment]
I guess you didn't read the readme isn't it?

**Comment by lalapetizoo** [comment]
> I guess you didn't read the readme isn't it?

I did and I'm using the HBL nsp.

**Comment by Cpasjuste** [comment]
Please try with this HBL NSP: https://gbatemp.net/threads/homebrew-menu-loader-legal-nsp.518433/
