### ISSUE TITLE
Special characters may cause Video not to play 

### ISSUE THREAD

**Issue by Cybernatus** [Cpasjuste/pplay#8]
Hello,

While using a remote HTTP server to retrieve a videos listing, it appears that some unicode characters such like "ç,é,è,à" aren't showing correctly on screen, sometimes resulting in weird behavior when trying to play them.

The most problematic one I've encountered which will always result in the file not playing and sometimes freeze Pplay is ' . I know this apostrophe is often moved out from files names due to its problematic nature, but it's a thing many files could still have it embedded, especially in a language such as French.  

I would then appreciate to see them supported inside the player, or for the least not to cause Pplay to hang and refuse to play a video because of the patterns.

Thanks already.

**Comment by Cpasjuste** [comment]
It will be worked on a the near future.

**Comment by Cybernatus** [comment]
This issue has been addressed and fixed in v2.1 . Thank you very much! <3
