### ISSUE TITLE
Cyan screen crash started recently

### ISSUE THREAD

**Issue by mrcookiestime** [Cpasjuste/pplay#9]
pPlay was working perfectly until I used it in docked mode and at first it started crashing the app in docked and handheld mode but now it crashes with a cyan screen which needs a reboot to get rid of.

**Comment by Cpasjuste** [comment]
Hi, did you solve the problem? Could you explain when it crash (at load, when playing a video..).

**Comment by Cpasjuste** [comment]
I think it's not related to pPlay, maybe your setup? Closing as no answer and no other report of this problem.
